Increase verbosity of "Premature end of potential file" error message
potfit/potfit pull request #75
Opened 2020-10-13 11:10 UTC by p-bro

This pull request improves the usefulness of the error message of running out of data on reading tabulated potential files (format 3 and 4). 

I may have botched up the pull request commit messages.

2020-10-13 17:09 UTC, dschopf requested changes
Changes look good except for the duplicate ADP lines.

2020-10-13 17:09 UTC, dschopf commented on src/potential_input_f3.c
> +        error(1, "Premature end of potential file %s\n(no ADP-d grad, pot %d)\n",
```suggestion
        error(1, "Premature end of potential file %s\n(no s-band rho grad, pot %d)\n",
```

2020-10-13 17:09 UTC, dschopf commented on src/potential_input_f3.c
> +        error(1, "Premature end of potential file %s\n(no ADP-d values, pot %d line %d)\n",
```suggestion
        error(1, "Premature end of potential file %s\n(no s-band rho values, pot %d line %d)\n",
```

2020-10-13 17:09 UTC, dschopf commented on src/potential_input_f3.c
> +        error(1, "Premature end of potential file %s\n(no ADP-q grad, pot %d)\n",
```suggestion
        error(1, "Premature end of potential file %s\n(no s-band F grad, pot %d)\n",
```

2020-10-15 09:11 UTC, p-bro commented
Oops. Cut and paste error.

2020-10-16 07:34 UTC, dschopf approved these changes

2021-11-10 16:34 UTC, merged